import 'dart:async';
import 'dart:math';
import 'package:sensors_plus/sensors_plus.dart';
import '../../../core/constants/app_constants.dart';
import '../models/swing_data.dart';

/// ============================================================
/// SensorService
/// ============================================================
/// The bridge between the phone's hardware sensors and our app.
///
/// HOW IT WORKS:
///   1. Subscribes to accelerometer and gyroscope streams.
///   2. On every reading it calculates:
///        - acceleration magnitude (from accelerometer x,y,z)
///        - estimated force (F = m × a)
///        - rotation angle (accumulated from gyroscope)
///        - peak acceleration and peak force (max seen so far)
///        - swing detection (is acceleration above threshold?)
///   3. Exposes a `Stream<SwingData>` that the Cubit listens to.
///
/// WHY a service layer?
/// - Separates "how we get data" from "how we manage state".
/// - If we swap sensors_plus for another package, only this
///   file changes — the rest of the app stays untouched.
/// ============================================================

class SensorService {
  // ── Internal state ──

  /// The mass used for F = m × a. Can be updated by the user.
  double _racketMassKg = AppConstants.defaultRacketMassKg;

  /// StreamController that broadcasts SwingData to any listener.
  final _swingDataController = StreamController<SwingData>.broadcast();

  /// Subscriptions to the raw sensor streams (so we can cancel later).
  StreamSubscription? _accelSubscription;
  StreamSubscription? _gyroSubscription;

  /// Latest raw values from each sensor.
  double _accelX = 0, _accelY = 0, _accelZ = 0;
  double _gyroX = 0, _gyroY = 0, _gyroZ = 0;

  /// Accumulated rotation angle (degrees).
  double _totalRotation = 0;

  // ── Peak tracking ──
  // These remember the HIGHEST values seen during the recording.
  // This is what the assignment means by "the force generated by
  // swinging" — the peak, not the last instantaneous reading.
  double _maxAcceleration = 0;
  double _maxForce = 0;

  // ── Public API ──

  /// The stream that the Cubit will listen to.
  Stream<SwingData> get swingDataStream => _swingDataController.stream;

  /// Updates the racket mass (e.g., when the user adjusts the slider).
  void setRacketMass(double massKg) {
    _racketMassKg = massKg;
  }

  /// Returns the current racket mass.
  double get racketMass => _racketMassKg;

  /// Starts reading from the phone sensors.
  void startListening() {
    final interval = Duration(milliseconds: AppConstants.sensorIntervalMs);

    // ── Accelerometer ──
    // userAccelerometer removes gravity, giving us only the
    // acceleration caused by the user's hand movement.
    _accelSubscription = userAccelerometerEventStream(
      samplingPeriod: interval,
    ).listen((event) {
      _accelX = event.x;
      _accelY = event.y;
      _accelZ = event.z;

      // Every time we get a new accelerometer reading,
      // combine it with the latest gyroscope data and emit.
      _emitSwingData();
    });

    // ── Gyroscope ──
    _gyroSubscription = gyroscopeEventStream(
      samplingPeriod: interval,
    ).listen((event) {
      _gyroX = event.x;
      _gyroY = event.y;
      _gyroZ = event.z;

      // Accumulate rotation: gyro gives rad/s, multiply by interval
      // in seconds, then convert radians → degrees.
      final double dtSeconds = AppConstants.sensorIntervalMs / 1000.0;
      final double angularSpeed = sqrt(
        _gyroX * _gyroX + _gyroY * _gyroY + _gyroZ * _gyroZ,
      );
      _totalRotation += angularSpeed * dtSeconds * (180 / pi);
    });
  }

  /// Stops reading from sensors and cleans up resources.
  void stopListening() {
    _accelSubscription?.cancel();
    _gyroSubscription?.cancel();
  }

  /// Resets ALL accumulated values (for starting a new swing).
  void reset() {
    _totalRotation = 0;
    _maxAcceleration = 0;
    _maxForce = 0;
    _accelX = 0;
    _accelY = 0;
    _accelZ = 0;
    _gyroX = 0;
    _gyroY = 0;
    _gyroZ = 0;

    // Emit a zeroed-out reading so the UI resets
    _swingDataController.add(SwingData.empty());
  }

  /// Releases all resources.
  void dispose() {
    stopListening();
    _swingDataController.close();
  }

  // ── Private helpers ──

  /// Combines the latest sensor values, computes derived metrics,
  /// and pushes a new SwingData onto the stream.
  void _emitSwingData() {
    // 1. Calculate total acceleration magnitude
    final double acceleration = sqrt(
      _accelX * _accelX + _accelY * _accelY + _accelZ * _accelZ,
    );

    // 2. Apply Newton's second law: F = m × a
    final double force = _racketMassKg * acceleration;

    // 3. Update peak values — keep the highest we've ever seen
    if (acceleration > _maxAcceleration) {
      _maxAcceleration = acceleration;
    }
    if (force > _maxForce) {
      _maxForce = force;
    }

    // 4. Detect swing: is the acceleration above the threshold?
    final bool swingDetected =
        acceleration >= AppConstants.swingDetectionThreshold;

    // 5. Build the data object and push it out
    final data = SwingData(
      acceleration: acceleration,
      force: force,
      rotationAngle: _totalRotation,
      maxAcceleration: _maxAcceleration,
      maxForce: _maxForce,
      swingDetected: swingDetected,
      accelerometerX: _accelX,
      accelerometerY: _accelY,
      accelerometerZ: _accelZ,
      gyroscopeX: _gyroX,
      gyroscopeY: _gyroY,
      gyroscopeZ: _gyroZ,
    );

    _swingDataController.add(data);
  }
}
