import 'dart:async';
import 'dart:math';
import 'package:flutter/services.dart';
import '../../../core/constants/app_constants.dart';
import '../models/swing_data.dart';

/// ============================================================
/// SensorService
/// ============================================================
/// The bridge between the phone's hardware sensors and our app.
///
/// HOW IT WORKS:
///   1. Subscribes to native Android EventChannel streams for
///      accelerometer (gravity-removed) and gyroscope data.
///   2. On every reading it calculates:
///        - acceleration magnitude (from accelerometer x,y,z)
///        - estimated force (F = m × a)
///        - rotation angle (accumulated from gyroscope)
///        - peak acceleration and peak force (max seen so far)
///        - swing detection (is acceleration above threshold?)
///   3. Exposes a `Stream<SwingData>` that the Cubit listens to.
///
/// WHY a service layer?
/// - Separates "how we get data" from "how we manage state".
/// - Sensor data comes from native Android (Kotlin) via EventChannel
///   platform channels — SensorManager APIs read the hardware directly.
/// - If the native implementation changes, only this file is updated.
///
/// NATIVE CHANNELS:
///   • com.example.flutter_project/accelerometer
///       TYPE_LINEAR_ACCELERATION — gravity removed, in m/s².
///   • com.example.flutter_project/gyroscope
///       TYPE_GYROSCOPE — angular velocity, in rad/s.
/// ============================================================

class SensorService {
  // ── EventChannel definitions ──

  /// Channel for gravity-removed linear acceleration (matches the previous
  /// sensors_plus userAccelerometerEventStream behaviour).
  static const _accelChannel = EventChannel(
    'com.example.flutter_project/accelerometer',
  );

  /// Channel for gyroscope angular velocity.
  static const _gyroChannel = EventChannel(
    'com.example.flutter_project/gyroscope',
  );

  // ── Internal state ──

  /// The mass used for F = m × a. Can be updated by the user.
  double _racketMassKg = AppConstants.defaultRacketMassKg;

  /// StreamController that broadcasts SwingData to any listener.
  final _swingDataController = StreamController<SwingData>.broadcast();

  /// Subscriptions to the raw sensor streams (so we can cancel later).
  StreamSubscription? _accelSubscription;
  StreamSubscription? _gyroSubscription;

  /// Latest raw values from each sensor.
  double _accelX = 0, _accelY = 0, _accelZ = 0;
  double _gyroX = 0, _gyroY = 0, _gyroZ = 0;

  /// Accumulated rotation angle (degrees).
  double _totalRotation = 0;

  // ── Peak tracking ──
  // These remember the HIGHEST values seen during the recording.
  // This is what the assignment means by "the force generated by
  // swinging" — the peak, not the last instantaneous reading.
  double _maxAcceleration = 0;
  double _maxForce = 0;

  // ── Public API ──

  /// The stream that the Cubit will listen to.
  Stream<SwingData> get swingDataStream => _swingDataController.stream;

  /// Updates the racket mass (e.g., when the user adjusts the slider).
  void setRacketMass(double massKg) {
    _racketMassKg = massKg;
  }

  /// Returns the current racket mass.
  double get racketMass => _racketMassKg;

  /// Starts reading from the phone sensors via native Android EventChannels.
  ///
  /// The sampling period is configured on the native side (50 ms / 20 Hz),
  /// matching AppConstants.sensorIntervalMs.
  void startListening() {
    // ── Accelerometer ──
    // Gravity-removed linear acceleration (TYPE_LINEAR_ACCELERATION).
    // The native side sends [x, y, z] as a List<double>.
    _accelSubscription = _accelChannel.receiveBroadcastStream().listen((event) {
      final data = event as List;
      _accelX = (data[0] as num).toDouble();
      _accelY = (data[1] as num).toDouble();
      _accelZ = (data[2] as num).toDouble();

      // Every time we get a new accelerometer reading,
      // combine it with the latest gyroscope data and emit.
      _emitSwingData();
    });

    // ── Gyroscope ──
    // Angular velocity in rad/s (TYPE_GYROSCOPE).
    // The native side sends [x, y, z] as a List<double>.
    _gyroSubscription = _gyroChannel.receiveBroadcastStream().listen((event) {
      final data = event as List;
      _gyroX = (data[0] as num).toDouble();
      _gyroY = (data[1] as num).toDouble();
      _gyroZ = (data[2] as num).toDouble();

      // Accumulate rotation: gyro gives rad/s, multiply by interval
      // in seconds, then convert radians → degrees.
      const double dtSeconds = AppConstants.sensorIntervalMs / 1000.0;
      final double angularSpeed = sqrt(
        _gyroX * _gyroX + _gyroY * _gyroY + _gyroZ * _gyroZ,
      );
      _totalRotation += angularSpeed * dtSeconds * (180 / pi);
    });
  }

  /// Stops reading from sensors and cleans up resources.
  ///
  /// Cancelling the stream subscriptions triggers [onCancel] on the native
  /// SensorStreamHandler, which immediately unregisters the hardware sensor
  /// listener — preventing battery drain or stale registrations.
  void stopListening() {
    _accelSubscription?.cancel();
    _accelSubscription = null;
    _gyroSubscription?.cancel();
    _gyroSubscription = null;
  }

  /// Resets ALL accumulated values (for starting a new swing).
  void reset() {
    _totalRotation = 0;
    _maxAcceleration = 0;
    _maxForce = 0;
    _accelX = 0;
    _accelY = 0;
    _accelZ = 0;
    _gyroX = 0;
    _gyroY = 0;
    _gyroZ = 0;

    // Emit a zeroed-out reading so the UI resets
    _swingDataController.add(SwingData.empty());
  }

  /// Releases all resources.
  void dispose() {
    stopListening();
    _swingDataController.close();
  }

  // ── Private helpers ──

  /// Combines the latest sensor values, computes derived metrics,
  /// and pushes a new SwingData onto the stream.
  void _emitSwingData() {
    // 1. Calculate total acceleration magnitude
    final double acceleration = sqrt(
      _accelX * _accelX + _accelY * _accelY + _accelZ * _accelZ,
    );

    // 2. Apply Newton's second law: F = m × a
    final double force = _racketMassKg * acceleration;

    // 3. Update peak values — keep the highest we've ever seen
    if (acceleration > _maxAcceleration) {
      _maxAcceleration = acceleration;
    }
    if (force > _maxForce) {
      _maxForce = force;
    }

    // 4. Detect swing: is the acceleration above the threshold?
    final bool swingDetected =
        acceleration >= AppConstants.swingDetectionThreshold;

    // 5. Build the data object and push it out
    final data = SwingData(
      acceleration: acceleration,
      force: force,
      rotationAngle: _totalRotation,
      maxAcceleration: _maxAcceleration,
      maxForce: _maxForce,
      swingDetected: swingDetected,
      accelerometerX: _accelX,
      accelerometerY: _accelY,
      accelerometerZ: _accelZ,
      gyroscopeX: _gyroX,
      gyroscopeY: _gyroY,
      gyroscopeZ: _gyroZ,
    );

    _swingDataController.add(data);
  }
}
