// ============================================================
// SwingData Model
// ============================================================
// This class represents a single snapshot of swing data captured
// from the phone sensors at one moment in time.
//
// It holds both LIVE (instantaneous) values and PEAK (maximum
// seen so far) values. The assignment asks for "the force
// generated by swinging" — which means the PEAK force, not
// the value at the instant you press stop.
// ============================================================

class SwingData {
  // ── Live (instantaneous) values ──

  /// Linear acceleration magnitude in m/s².
  /// Calculated as: sqrt(x² + y² + z²) from the accelerometer.
  final double acceleration;

  /// Estimated force in Newtons, using Newton's second law: F = m × a.
  final double force;

  /// Accumulated rotation angle in degrees.
  /// Derived from the gyroscope sensor readings.
  final double rotationAngle;

  // ── Peak (maximum) values ──
  // These track the highest acceleration and force seen during
  // the entire recording session. This is what matters for the
  // assignment: "calculate the force generated by swinging".

  /// The highest acceleration recorded so far (m/s²).
  final double maxAcceleration;

  /// The highest force recorded so far (N).
  final double maxForce;

  // ── Swing detection ──

  /// Whether the current acceleration exceeds the swing threshold.
  /// True = the user is actively swinging, not just holding the phone.
  final bool swingDetected;

  // ── Raw sensor values ──

  /// Raw accelerometer values for each axis.
  final double accelerometerX;
  final double accelerometerY;
  final double accelerometerZ;

  /// Raw gyroscope values for each axis (rad/s).
  final double gyroscopeX;
  final double gyroscopeY;
  final double gyroscopeZ;

  const SwingData({
    required this.acceleration,
    required this.force,
    required this.rotationAngle,
    required this.maxAcceleration,
    required this.maxForce,
    required this.swingDetected,
    required this.accelerometerX,
    required this.accelerometerY,
    required this.accelerometerZ,
    required this.gyroscopeX,
    required this.gyroscopeY,
    required this.gyroscopeZ,
  });

  /// Factory constructor to create a "zero" / empty reading.
  /// Used as the initial state before any sensor data arrives.
  factory SwingData.empty() {
    return const SwingData(
      acceleration: 0,
      force: 0,
      rotationAngle: 0,
      maxAcceleration: 0,
      maxForce: 0,
      swingDetected: false,
      accelerometerX: 0,
      accelerometerY: 0,
      accelerometerZ: 0,
      gyroscopeX: 0,
      gyroscopeY: 0,
      gyroscopeZ: 0,
    );
  }
}
